### ISSUE TITLE
Status updates?

### ISSUE THREAD

**Issue by UnitedMarsupials-zz** [LenShustek/RedLINK-Sniffer#1]
Hello! I've installed two RedLink sensors recently, both communicating to a new thermostat. I'd love to be able to log the sensors' readings on my computer (running FreeBSD), but the only "official" way to do that is to buy a [RedLink "gateway"](https://www.amazon.com/Honeywell-THM6000R1002-Enabled-Internet-Gateway/dp/B006BD1K4A) (which would've been fine) and then download the readings from Honeywell's web-site. That latter part annoys me to no end -- Honeywell needn't know the temperatures in my house...

Searching the Internet for "Redlink sniff" brought me here. What is the status of your project?

Is there a hardware I can already buy, which, connected to a computer's port (COM, USB?) would allow some software to read the data, that sensors are sending to the thermostat? I'm a software guy, so any modifications to hardware would have to be very well enumerated and clearly spelled-out :-)

Alternatively, have you considered intercepting not the radio-signals, but the TCP-packets, that their "gateway" sends to Honeywell? Folks trying to hack AcuRite bridge seem to have made [some progress](http://moderntoil.com/?p=794) with that approach.

**Comment by LenShustek** [comment]
Unfortunately I was not able to make progress on reverse-engineering the RedLINK wireless communication, so I abandoned this project. I actually ripped out all my RedLINK equipment (!) and implemented an entirely different approach to solve my particular problem by building custom wireless sensors. If you're curious, see https://github.com/LenShustek/tempsensor.

I had tried briefly to look at the TCP packets that the RedLINK gateway sends, but I couldn't get around the encryption. Someone more knowledgeable about modern protocols might be able to do better at that.

Good luck!
